[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "https://ciselab.netlify.app/*"
  to = "https://www.ciselab.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ciselab.com/*"
  to = "https://www.ciselab.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ciselab.com/*"
  to = "https://www.ciselab.nl/:splat"
  status = 301
  force = true
